### ISSUE TITLE
Error running `gh ji`

### ISSUE THREAD

**Issue by jwu910** [node-gh/gh-jira#78]
```>> $ gh ji
TypeError: Cannot read property 'user' of undefined
    at Jira.normalizeOptions (/home/joshua/.nvm/versions/node/v10.16.0/lib/node_modules/gh-jira/bin/jira.js:775:59)
    at Jira.run (/home/joshua/.nvm/versions/node/v10.16.0/lib/node_modules/gh-jira/bin/jira.js:180:14)
    at getCommand.fork (/home/joshua/.nvm/versions/node/v10.16.0/lib/node_modules/gh/lib/cmd.js:175:39)
```

@protoEvangelion is gh-jira not compatible with recent releases of node-gh?

I just updated gh to 2.8.3 but gh-jira is still at 1.0.7.

I haven't been able to get gh-jira to work with node-gh in a while. Has this been on the radar? I vaguely remember the security changes that were made to the JIRA server we use caused issues in the past, but wondering that was a one time fluke or if it's a reproducible problem.

Thanks!

**Comment by protoEvangelion** [comment]
Hey @jwu910 👋 I haven't been maintaining gh-jira, for a while, however I did test it successfully for v2 of gh with a manual workaround.

I'm pretty sure your issues have something to do with Jira's required oauth handshake. In the past we could just send over basic auth (_user & pass_) but they don't allow that method of auth any more.

Let me know if you have any ideas of how to approach this!

**Comment by jwu910** [comment]
I haven't worked with this type of functionality yet, and am interested, but at this moment--no ideas, sorry.

I remember this came up when we made changes to our JIRA auth, so maybe it's still a problem. Not that big a issue. You can close this or maybe consider a request for comments/help wanted

**Comment by protoEvangelion** [comment]
That sounds about right. Thanks for raising the issue! I'll leave it open.

**Comment by protoEvangelion** [comment]
Side note, I'm actually thinking of deprecating this plugin along with the concept of plugins. The same thing can be accomplished through hooks (ie _state sharing_). Any thoughts?

**Comment by jwu910** [comment]
I dont think its a critical package, it's a great workflow benefit, but it was really only saving a couple clicks. I think post-PR scripts with gh can help partially automate the use case I wanted to solve anyways. 

Thanks for the consideration! Hope all is well!

Feel free to close
